### PR TITLE
feat: adapt the rules

### PR DESCRIPTION
**Pull request by david-paulus-saad**

### CODE REVIEW

**Comment by KhaledSakr** [comment]
@david-paulus-saad I think we can tag for review someone that was in the meeting where you discussed the rules. They would be more aware of the needed changes there

**Comment by mowaleed96** [comment]
LGTM.
Although I think the reviewer check is missing

**Comment by david-paulus-saad** [comment]
@mowaleed96 does the reviewer check make sense?

**Comment by mowaleed96** [comment]
@david-paulus-saad 
Yes, as the tickets are moved from inprogress to in review only when there's someone tagged for review
the old check was for the assignee which was wrong, and we wanted to make it for the reviewer

**Comment by david-paulus-saad** [comment]
@mowaleed96  done

**Review by mowaleed96 — APPROVED** [review]
Great job :+1:

**Pull request merged**
